### ISSUE TITLE
Symfony 6.2 compatibility

### ISSUE THREAD

**Issue by Punt13140** [ecphp/cas-bundle#76]
## Steps required to reproduce the problem

1. Create a new Symfony project 
`symfony new myproject --version="6.2.*" --webapp`
2. Install the bundle
`composer require ecphp/cas-bundle`

## Result
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ecphp/cas-bundle[2.5.0, ..., 2.5.4] require ecphp/cas-lib 1.1.* -> satisfiable by ecphp/cas-lib[1.1.0, ..., 1.1.9].
    - ecphp/cas-lib[1.1.0, ..., 1.1.7] require psr/cache ^1.0.1 -> found psr/cache[1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - ecphp/cas-lib[1.1.8, ..., 1.1.9] require psr/http-factory-implementation ^1 -> could not be found in any version, but the following packages provide it:
      - guzzlehttp/psr7 PSR-7 message implementation that also provides common utility methods
      - nyholm/psr7 A fast PHP7 implementation of PSR-7
      - http-interop/http-factory-guzzle An HTTP Factory using Guzzle PSR7
      - laminas/laminas-diactoros PSR HTTP Message implementations
      - zendframework/zend-diactoros PSR HTTP Message implementations
      - slim/psr7 Strict PSR-7 implementation
      - typo3/cms-core TYPO3 CMS Core
      - tuupola/http-factory Lightweight autodiscovering PSR-17 HTTP factories
      - nimbly/capsule Capsule is a simple PSR-7 HTTP message and PSR-17 HTTP factory implementation.
      - httpsoft/http-message Strict and fast implementation of PSR-7 and PSR-17
      - mileschou/psr The support library for PSR
      - oro/platform Business Application Platform (BAP)
      - sunrise/http-message HTTP message wrapper for PHP 7.4+ based on RFC-7230, PSR-7 and PSR-17
      - php-extended/php-http-message-factory-psr17 An implementation of the psr-17 based on the php-http-message-psr7 library
      - typo3/cms TYPO3 CMS is a free open source Content Management Framework initially created by Kasper Skaarhoj an
      - windwalker/uri Windwalker Uri package
      - bittyphp/http PSR-7 and PSR-17 HTTP implementation.
      - yiisoft/psr-dummy-provider PSR Dummy Provider
      - http-interop/http-factory-diactoros An HTTP Factory using Zend Diactoros
      - sunrise/http-factory HTTP factory for PHP 7.1+ based on PSR-17
      ... and 51 more.
      Consider requiring one of these to satisfy the psr/http-factory-implementation requirement.
    - Root composer.json requires ecphp/cas-bundle ^2.5 -> satisfiable by ecphp/cas-bundle[2.5.0, ..., 2.5.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by drupol** [comment]
Hello,

In the bottom of your log, the composer error say:  "Consider requiring one of these to satisfy the psr/http-factory-implementation requirement."

So, you _need_ a `psr/http-factory-implementation` before succeededing to install `ecphp/cas-bundle`.

Therefore, to fix your issue, you can do:

```
composer require ecphp/cas-bundle nyholm/psr7
```

Let me know if this is fixing your issue.

**Comment by Punt13140** [comment]
Hello,

Thank you for responding so quickly,
Yes it fixes my issue. 

Not related, I managed to install the bundle, but now I have trouble getting it to work, if I do this
```
    access_control:
         - { path: ^/, roles: ROLE_CAS_AUTHENTICATED }
```

This does not redirect me to the login page. Did I miss something on your documentation ?

Thanks

**Comment by drupol** [comment]
Hello,

You need to update your `security.yaml` and define the `entry_point`.

Something like this (be careful, I haven't tested that)

```yaml
security:
    password_hashers:
        # Our user class and the algorithm we'll use to encode passwords
        # 'auto' means to let Symfony choose the best possible password hasher (Argon2 or Bcrypt)
        # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # https://symfony.com/doc/current/security/user_provider.html
        # In this example, users are stored via Doctrine in the database
        # To see the users at src/App/DataFixtures/ORM/LoadFixtures.php
        # To load users from somewhere else: https://symfony.com/doc/current/security/user_provider.html#creating-a-custom-user-provider
        database_users:
            entity: { class: App\Entity\User, property: username }

    # https://symfony.com/doc/current/security.html#a-authentication-firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # this firewall does not have a 'pattern' option because it applies to all URLs
            lazy: true
            provider: cas
            custom_authenticator: EcPhp\CasBundle\Security\CasAuthenticator

            # This allows the user to login by submitting a username and password
            # Reference: https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                # The route name that the login form submits to
                check_path: cas_bundle_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: cas_bundle_login
                # Secure the login form against CSRF
                # Reference: https://symfony.com/doc/current/security/csrf.html
                enable_csrf: true
                # The page users are redirect to when there is no previous page stored in the
                # session (for example when the users access directly to the login page).
                default_target_path: blog_index

            # This option allows users to choose to stay logged in for longer than
            # the session lasts using a cookie. Reference: https://symfony.com/doc/current/security/remember_me.html
            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds
                # by default, the feature is enabled by checking a checkbox in the
                # login form , uncomment the following line to always enable it.
                #always_remember_me: true

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: homepage

                # Secure the logout against CSRF
                csrf_parameter: logout
                csrf_token_generator: security.csrf.token_manager

            # needed because in tests we redefine the 'main' firewall to use
            # HTTP Basic instead of the login form, so this firewall has
            # multiple authenticators
            # See https://symfony.com/doc/current/security/experimental_authenticators.html#configuring-the-authentication-entry-point
            entry_point: 'form_login'

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    # this configuration simplifies testing URLs protected by the security mechanism
    # See https://symfony.com/doc/current/testing/http_authentication.html
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

        firewalls:
            main:
                http_basic: ~
```

**Comment by Punt13140** [comment]
I'm sorry, I'm not able to make it work. The entry point part is working, but now I have an infinite loop on `http://127.0.0.1:8000/cas/login`... 

Do you have a project or a test project with the bundle installed where I can do some digging ?

Thanks for your answers again.

**Comment by drupol** [comment]
Hi,

Could you please share your `cas_bundle` config ?

**Comment by Punt13140** [comment]
I'm using the default configuration right now. I just want to setup the bundle, then I'll try to use it with my CAS.

```
security:
    providers:
        cas:
            id: cas.userprovider
```

And here's my security.yaml

```
security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: cas
            custom_authenticator: EcPhp\CasBundle\Security\CasAuthenticator
            form_login:
                check_path: cas_bundle_login
                login_path: cas_bundle_login
                enable_csrf: true
                default_target_path: app_home
            entry_point: form_login
            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds
#            logout:
#                path: security_logout
#                target: homepage
#                csrf_parameter: logout
#                csrf_token_generator: security.csrf.token_manager

    access_control:
         - { path: ^/, roles: ROLE_CAS_AUTHENTICATED }

```

**Comment by drupol** [comment]
I think the issue comes from the `cas_bundle` configuration, can you share it?

**Comment by Punt13140** [comment]
Here you go :

```
cas:
    base_url: https://heroku-cas-server.herokuapp.com/cas
    protocol:
        login:
            path: /login
            allowed_parameters:
                - service
                - renew
                - gateway
            default_parameters:
                service: https://my-app/homepage
        serviceValidate:
            path: /p3/serviceValidate
            allowed_parameters:
                - format
                - pgtUrl
                - service
                - ticket
            default_parameters:
                format: JSON
                pgtUrl: https://my-app/casProxyCallback
        logout:
            path: /logout
            allowed_parameters:
                - service
            default_parameters:
                service: https://my-app/homepage
        proxy:
            path: /proxy
            allowed_parameters:
                - targetService
                - pgt
        proxyValidate:
            path: /proxyValidate
            allowed_parameters:
                - format
                - pgtUrl
                - service
                - ticket
            default_parameters:
                format: JSON
                pgtUrl: https://my-app/casProxyCallback
```

**Comment by drupol** [comment]
I see that the `service` parameter in the login definition points towards the homepage, it's fine.

However, I see that you enabled `pgtUrl`, I would disable that at first.
When you enable `pgtUrl`, authentication become more strict and you need to have a fully accessible app in HTTPS by the CAS server so it can store the PGTs.
I would recommend to disable that by just removing the lines starting with `pgtUrl` at first.

Let's try like that, and if it doesn't work, then a logfile will be useful.

**Comment by Punt13140** [comment]
cas_bundle.yaml
```yaml
cas:
    base_url: https://casserver.herokuapp.com/cas
    protocol:
        login:
            path: /login
            allowed_parameters:
                - service
                - renew
                - gateway
            default_parameters:
                service: https://my-app/homepage
        serviceValidate:
            path: /p3/serviceValidate
            allowed_parameters:
                - format
                - service
                - ticket
            default_parameters:
                format: JSON
        logout:
            path: /logout
            allowed_parameters:
                - service
            default_parameters:
                service: https://my-app/homepage
        proxy:
            path: /proxy
            allowed_parameters:
                - targetService
                - pgt
        proxyValidate:
            path: /proxyValidate
            allowed_parameters:
                - format
                - service
                - ticket
            default_parameters:
                format: JSON

```

I dumped the return of `supports()` in CasAuthenticator and it returns false.
```php
$this
            ->cas
            ->withServerRequest($this->toPsr($request))
            ->supportAuthentication(); // = false
```



If I force a `return true;`, in `authenticate()`

```php
        $response = $this
            ->cas
            ->withServerRequest($this->toPsr($request))
            ->requestTicketValidation();

```

`$response` is `null`.

Here's the log

```
[2023-01-18T14:43:52.017439+00:00] request.INFO: Matched route "app_home". {"route":"app_home","route_parameters":{"_route":"app_home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-01-18T14:43:52.018894+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":3} []
[2023-01-18T14:43:52.018924+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"EcPhp\\CasBundle\\Security\\CasAuthenticator"} []
[2023-01-18T14:43:52.019078+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"EcPhp\\CasBundle\\Security\\CasAuthenticator"} []
[2023-01-18T14:43:52.019098+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-01-18T14:43:52.019113+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-01-18T14:43:52.019127+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-01-18T14:43:52.019145+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-01-18T14:43:52.021429+00:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /Users/punt/Dev/amu/php/tmp/amu624/vendor/symfony/security-http/Firewall/AccessListener.php:91)"} []
[2023-01-18T14:43:52.021487+00:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator":[]}} []
[2023-01-18T14:43:52.053276+00:00] request.INFO: Matched route "cas_bundle_login". {"route":"cas_bundle_login","route_parameters":{"_route":"cas_bundle_login","_controller":"EcPhp\\CasBundle\\Controller\\Login"},"request_uri":"http://127.0.0.1:8000/cas/login","method":"GET"} []
[2023-01-18T14:43:52.054626+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":3} []
[2023-01-18T14:43:52.054657+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"EcPhp\\CasBundle\\Security\\CasAuthenticator"} []
[2023-01-18T14:43:52.054759+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"EcPhp\\CasBundle\\Security\\CasAuthenticator"} []
[2023-01-18T14:43:52.054779+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-01-18T14:43:52.054795+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-01-18T14:43:52.054809+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-01-18T14:43:52.054824+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-01-18T14:43:52.056315+00:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /Users/punt/Dev/amu/php/tmp/amu624/vendor/symfony/security-http/Firewall/AccessListener.php:91)"} []
[2023-01-18T14:43:52.056370+00:00] security.DEBUG: Calling Authentication entry point. {"entry_point":{"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator":[]}} []
[2023-01-18T14:43:52.089314+00:00] request.INFO: Matched route "cas_bundle_login". {"route":"cas_bundle_login","route_parameters":{"_route":"cas_bundle_login","_controller":"EcPhp\\CasBundle\\Controller\\Login"},"request_uri":"http://127.0.0.1:8000/cas/login","method":"GET"} []


// loop...
```

**Comment by drupol** [comment]
Curious. Ok, I will do it on my side and come back to you.

**Comment by Punt13140** [comment]
More information:
I tried to setup the bundle with Symfony 5.4 and PHP 7.4 and I have the same issue...

With Symfony 6.2, I was using PHP 8.1.

either there is a problem with my configuration, or with the bundle... If you want more information, let me know. I can provide you a test project with my configuration if you want.

**Comment by drupol** [comment]
Hi,

I didn't give much feedback since I was off, until Wednesday of this week.

Expect news from me on starting from Wednesday.

Thanks.

**Comment by drupol** [comment]
Hello,

I successfully setup CAS Bundle on the Symfony Demo:

![image](https://user-images.githubusercontent.com/252042/214530166-e350f29c-7d69-4d35-8c8b-ea72762b62a2.png)

Would you be available for a quick visio (max 15min)?

**Comment by Punt13140** [comment]
Yes I am. Send me a link. I'm not available from 11:30am to 1pm

**Comment by drupol** [comment]
Sending you an email

**Comment by Punt13140** [comment]
Thanks for your time again !

There is indeed an infinite loop when you want to have a 100% authenticated CAS application. 
To correct this, you just have to make "public" the routes to your bundle:

```yaml
security:
    # ...
    access_control:
        - { path: ^/cas, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_CAS_AUTHENTICATED }
```

Here is the full security configuration:

```yaml
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: cas
            custom_authenticator: EcPhp\CasBundle\Security\CasAuthenticator
            form_login:
                check_path: cas_bundle_login
                login_path: cas_bundle_login
            entry_point: form_login
            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds
            logout:
                path: security_logout
                target: homepage
                csrf_parameter: logout
                csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/cas, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_CAS_AUTHENTICATED }
```

If you want more information, let me know.
